[package]
name = "volga"
version = "0.2.3"
edition = "2021"
authors = ["Roman Emreis <roman.emreis@outlook.com>"]
license = "MIT"
repository = "https://github.com/RomanEmreis/volga"
description = "Easy & Fast Web Framework for Rust"
documentation = "https://docs.rs/volga"
readme = "README.md"
homepage = "https://romanemreis.github.io/volga-docs"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = "0.7.12"
chrono = "0.4.38"
http = "1.1.0"
httparse = "1.9.5"
bytes = "1.8.0"
mime = "0.3.17"
serde_json = "1.0.132"
serde = { version = "1.0.214", features = ["derive"] }

[dev-dependencies]
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
